name: Tests

on: [push]

jobs:
  main:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18]

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm install
      - run: sudo apt-get install -y expect
      - run: pnpm playwright install --with-deps
      - name: Run E2E tests
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          TERM: xterm # fix for tput
        run: pnpm nx affected:e2e --verbose
      - name: Run other tests
        run: pnpm nx affected:test --verbose
