name: E2E App

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.5.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install App
        working-directory: templates/default
        run: |
          npm install
          npx playwright install --with-deps
      - name: Run App in background
        working-directory: templates/default
        run: |
          ./testsetup.sh
          npm run build
          npm start &
        env:
          PORT: 3000
      - name: Run tests
        working-directory: templates/default
        run: |
          npm run test:e2e
        env:
          CI: true
